Refactor: modify detail post to be rendered in real time
j1y0ungyoon/gym-tivation pull request #9
Opened 2023-02-15 01:22 UTC by SeongYeongJu

## Refactor: modify detail post to be rendered in real time #3 
---
### feature/mapBoard -> dev
---
### RecruitDetail
- onSnapshot을 이용하여 실시간으로 변경 내용을 반영하도록 코드 변경
- 기존 useQuery로 getDoc을 했던 방식은 삭제
---
### RecruitPost
- router.push의 url에 post의 id만 표시되도록 변경

by @SeongYeongJu

2023-02-15 05:58 UTC, j1y0ungyoon requested changes
코멘트 확인 부탁드립니다.

2023-02-15 05:58 UTC, j1y0ungyoon commented on components/RecrutPost.tsx
>      );
파일명 오타가 있어요! 바꿔야 될 것 같아요!

2023-02-15 10:05 UTC, SeongYeongJu commented on components/RecrutPost.tsx
>      );
> 파일명 오타가 있어요! 바꿔야 될 것 같아요!

네 이후에 PR할 때 이 부분 고쳐서 PR 날리겠습니다. 일단 기능 문제는 없는 것 같네요!

2023-02-17 06:21 UTC, j1y0ungyoon approved these changes

2023-02-19 06:12 UTC, merged